### ISSUE TITLE
source a qwiic/stemma qt compatible connector

### ISSUE THREAD

**Issue by securelyfitz** [tigard-tools/tigard#17]
"JST SH 4 Pin (1.0mm pitch)"

JST part BM04B-SRSS-TB (vertical) or SM04B-SRSS-TB (right angle) 

Perhaps there's a cheaper compatible one?

**Comment by fharding1** [comment]
$0.09/PCS at quantity 100+

https://lcsc.com/product-detail/Wire-To-Board-Wire-To-Wire-Connector_JST-Sales-America-SM04B-SRSS-TB-LF-SN_C160404.html
