### ISSUE TITLE
Consider direction indicator symbols by pinouts

### ISSUE THREAD

**Issue by securelyfitz** [tigard-tools/tigard#19]
I've seen it on a few different boards, here's one example: 
https://cdn-shop.adafruit.com/1200x900/1431-07.jpg

It's likely pretty handy for a device like this where you're constantly moving connections around as a reference for direction of data.

That said, there's not much room so not sure it's feasible. Perhaps it should be added to the wiring harness heatshrink labels instead?

**Comment by fharding1** [comment]
Yeah I don't think there's much room, the wiring harnesses would probably be better.
