### ISSUE TITLE
Connect LA header's GND pins to GND

### ISSUE THREAD

**Issue by securelyfitz** [tigard-tools/tigard#21]
Working on a possibly related issue and discovered this, i assume they should be grounded. 

however, let's capture it here if there's a reason they're not.

**Comment by fharding1** [comment]
@securelyfitz oh, that's a really stupid mistake on my part. It's specified clearly in the BMB schematic. Will fix.

![image](https://user-images.githubusercontent.com/32021905/89365857-649c0980-d68a-11ea-950b-3a2d6cccce76.png)
