### ISSUE TITLE
Perhaps you would like an SMD version of the slide switch?

### ISSUE THREAD

**Issue by TomKeddie** [tigard-tools/tigard#27]
https://item.taobao.com/item.htm?spm=a230r.1.14.1.6d76278eeIhC1X&id=26754256644&ns=1&abbucket=20#detail

![O1CN01tpxokm1MPbibBjUJj_!!1716861427](https://user-images.githubusercontent.com/4367175/93165633-69b09780-f6d1-11ea-92a7-d410bec39d4e.jpg)

**Comment by securelyfitz** [comment]
Thanks, though we opted for the through-hole version for durability. We knew we wanted the most-used 2.54mm headers to be through-hole. The switches were probably next in line for heavy use, and since we knew we weren't going to be able to do all-smd assembly we figured it was the best choice.
