### ISSUE TITLE
LA and SPI headers (j6 and j4) are too close to be used by IDC-style cables at the same time.

### ISSUE THREAD

**Issue by securelyfitz** [tigard-tools/tigard#28]
V0.1 had them far enough apart for typical IDC cables to be edge-to-edge, V1.0 shifted them over 1.5mm to make room for the stemma/qwiic connector.

Temporary Workarounds:

1. Use the JTAG connector for spi/i2c when you want to observe
2. or use individually crimped style instead of IDC-style connectors on the spi/i2c header
3. reinforce with superglue, then clip 1.5mm off the edge of the 14-pin LA connector so that it fits but stays in one piece

Solution:
Shift it back over 1.5mm left for next revision. Not sure if this warrants a major revision. physical layout will change but pinouts will not.

**Comment by fharding1** [comment]
I don't think this necessitates a major rev either. I would consider moving one of the 2.54mm headers a major breaking change (since we have a test jig and people might make custom boards to access those pins), but not the LA header.
