### ISSUE TITLE
Documentation (I2C, minor)

### ISSUE THREAD

**Issue by hattesen** [tigard-tools/tigard#31]
The [Documentation I2C Quirks](https://github.com/tigard-tools/tigard#quirks) states: 

> "I2C depends on shared I/O lines using common emitter instead of push-pull-tristate I/O"

I2C is based on Open Collector (Open Drain), not "Common Emitter" (if such a thing even exists).

Thank you for a very polished and comprehensive product documentation 👍

**Comment by securelyfitz** [comment]
Thanks - will correct with a bunch of other minor edits i'll be pushing soon.

Glad to know people are reading the docs. Makes it worth writing them!

**Comment by securelyfitz** [comment]
finally, fixed in 91b9b72bf76c5e803ee3a8881cabcbd8f156a8c5. Thanks again for pointing this out
