### ISSUE TITLE
Schematic as PDF

### ISSUE THREAD

**Issue by hattesen** [tigard-tools/tigard#32]
Any chance of making the schematics available in PDF format?
(And while you are at it, move all Kicad related resources into a /kicad subdirectory, to remove the root folder clutter before it is too late). 

Yes, I know I can just clone, start up Kicad, and export to PDF myself, but it would be nice to have as a reference as part of the repository.

**Comment by fharding1** [comment]
They’re included in releases. Schematic PDFs are binary files that don’t belong in the source repo (like how you wouldn’t check in an executable).
