### ISSUE TITLE
BOM has wrong LCSC Part Number for LA Header

### ISSUE THREAD

**Issue by Matir** [tigard-tools/tigard#34]
The part numbers embedded in the KiCad schematic for the LA header do not match.  The 14-pin Samtec header is correct (FTSH-107-01-F-DV-K) but the LCSC Part Number (C448647) is for the 10 pin version (which is used for the SWD connector).

I can't find a matching LCSC part number, so maybe it needs to removed entirely?  (Or maybe you know the part number and I just can't use lcsc.com correctly.)

**Comment by fharding1** [comment]
Removing it seems like the right choice to me. I created a commit in the move-la-misc branch that should close this issue when merged into master.
