### ISSUE TITLE
Windows drivers

### ISSUE THREAD

**Issue by romain145** [tigard-tools/tigard#47]
Tigard V1.0 shows a warning in the Device Manager: "The drivers for this device are not installed".
Which driver should be used?

![Capture](https://user-images.githubusercontent.com/4060945/121165062-470e7200-c850-11eb-9060-b652045ea282.PNG)

![Capture2](https://user-images.githubusercontent.com/4060945/121165077-4970cc00-c850-11eb-978b-287fb7f45635.PNG)

**Comment by securelyfitz** [comment]
It depends on what you want to do. If you'd just like to access the serial port, then the [FTDI VCP](https://ftdichip.com/drivers/vcp-drivers/) drivers should work. If you're planning on using openOCD or circuitpython, you'll need to install a WinUSB driver, i believe using something like [zadig](https://zadig.akeo.ie/) as described [here](https://learn.adafruit.com/circuitpython-on-any-computer-with-ft232h/windows)
Let us know if you have any issues.
