### ISSUE TITLE
The package type of some capacitors

### ISSUE THREAD

**Issue by urockO** [tigard-tools/tigard#49]
I purchased the components on szlcsc.com according to the BOM file.
But some of the capacitors whose footprint is marked as **0402** are actually **0603**.
exmple:C71000
![1630303762794](https://user-images.githubusercontent.com/19217042/131293206-6949a6a4-9b29-4645-b78f-b0a6d516a2da.jpg)
![1630303910565](https://user-images.githubusercontent.com/19217042/131293446-7de4887f-3852-413f-8125-b96b1a9cc775.jpg)

Could I use CL10A225KQ8NNNC to replace CL05A225KQ5NSNC? or use another?
CL05A225KQ5NSNC :
![image](https://user-images.githubusercontent.com/19217042/131293944-d03804ba-5baa-4ca0-8d6c-3eb317f6dca6.png)

**Comment by securelyfitz** [comment]
Already fixed in 8173ad0a4263c88161fd51c056eb07aa513dfd12
