### ISSUE TITLE
Resistor between Pin 44 and Pin 46

### ISSUE THREAD

**Issue by Spikycloud** [tigard-tools/tigard#65]
Hi,

It's a such a great design, making it OHW is helping me learn HW design. I have a question tough, what's the use of R22 2K2 between BD5 and BD7 (avoid tri-state of SRST# ?)

Thank in advance.

**Comment by securelyfitz** [comment]
Glad you're finding it useful! good question, covered in #62 and #15. lmk if you want more detail.

**Comment by Spikycloud** [comment]
Thank you so much for the quick response.
