### ISSUE TITLE
SVG logo?

### ISSUE THREAD

**Issue by RagingRoosevelt** [tigard-tools/tigard#69]
Is there an SVG copy of the logo?  I was going to 3d print [this case](https://www.thingiverse.com/thing:5169952) for the Protocol Tool and the Bit Magic and wanted to embed the logo but I haven't seen SVGs available.

No worries if this was an active decision to not include.

**Comment by securelyfitz** [comment]
here you go!

![tigard 2020 08 15](https://github.com/tigard-tools/tigard/assets/5185686/caea0c31-1300-45ff-af0f-7d15d190d294)

**Comment by RagingRoosevelt** [comment]
Thanks!  [It worked really well](https://www.thingiverse.com/make:1163505) =D

![20240313_132857](https://github.com/tigard-tools/tigard/assets/6985440/22831729-316b-4be1-959c-78ad17629b18)

**Comment by securelyfitz** [comment]
Finally did mine! My first multicolor print. I think i should have done the logo smaller like yours.
![PXL_20241130_074716158.jpg](https://github.com/user-attachments/assets/5b6c7c68-1432-4636-a433-2e01854d76f0)
