### ISSUE TITLE
EEPROM contents available?

### ISSUE THREAD

**Issue by jknGH** [tigard-tools/tigard#72]
Hi there - are the original EEPROM contents available please? I have been doing some ... experimenting ... and I *may* need to revert to the original contents. I intended to save it but due to unfamiliarity with the tools my file may have been overwritten ;-(

Thanks, J^n

**Comment by securelyfitz** [comment]
Sorry i missed this issue!
I use ftdi_eeprom to flash them after they pass testing. Below is the config file - i think i may have made small changes to it on my flashing rig (rpi-based) that i ought to back up somewhere else. To use the config file, set a serial number and run:

`ftdi_eeprom --flash-eeprom tigard.conf`

tigard.conf:
```
vendor_id=0x403
product_id=0x6010
max_power=500
manufacturer="SecuringHardware"
product="Tigard V1.1"
self_powered=false  # Turn this off for bus powered
remote_wakeup=false # Turn this on for remote wakeup feature
use_serial=true     # Use the serial number string
in_is_isochronous=false     # In Endpoint is Isochronous
out_is_isochronous=false    # Out Endpoint is Isochronous
suspend_pull_downs=false    # Enable suspend pull downs for lower power
change_usb_version=false    # Change USB Version
usb_version=0x0200          # Only used when change_usb_version is enabled
eeprom_type=0x56

serial="TG11xxxx"

```

**Comment by jknGH** [comment]
Thanks very much!

I am experimenting in using TIGARD in an application where I want to swap the two ports over; I may have lost the original contents but wanted to make sure I could get back to that state if necessary, or when I am done...

Regards, jon N

**Comment by securelyfitz** [comment]
if you run into trouble, let me know. i'll close this issue for now.
